#!/usr/bin/env python3
"""Generate enc.h: the flag XOR-encoded with the build-time constant K. At
runtime the program re-masks this array with a random byte r and stores
dkey = K ^ r, so the effective decode key is only known in the running process.
Only shellcode running in the process can recover the flag; a static XOR of the
file will not work."""

FLAG = b"NCTF{rwx_shellcode_decoded_the_section}"
K = 0x2B


def main() -> None:
    enc = bytes(b ^ K for b in FLAG)
    body = ", ".join(f"0x{b:02x}" for b in enc)
    with open("enc.h", "w") as fh:
        fh.write("/* generated by gen.py -- do not edit */\n")
        fh.write(f"static const int enc_len = {len(enc)};\n")
        fh.write(f"static const unsigned char enc_src[{len(enc)}] = {{ {body} }};\n")


if __name__ == "__main__":
    main()
