#!/usr/bin/env python3
"""
Developer-only generator for the 'triple-wrap' reverse challenge.

The flag is wrapped in three layers before being embedded in the binary:

    1. ROT13 on ASCII letters
    2. XOR each byte with a repeating key ("wrapkey")
    3. Base64 encode the result

The compiled program stores only the base64 blob (which shows up in strings(1))
plus a decoy NCTF{...} string. At runtime it peels all three layers back to the
real flag and compares it to the user's input; it never prints the flag on its
own. Players must reverse the layer stack. This file is NOT shipped.
"""

import base64

FLAG = b"NCTF{peel_b64_rot13_x0r_layers}"
DECOY = b"NCTF{th1s_1s_n0t_th3_r34l_0ne}"
KEY = b"wrapkey"


def rot13(data):
    out = bytearray()
    for b in data:
        if 65 <= b <= 90:
            out.append((b - 65 + 13) % 26 + 65)
        elif 97 <= b <= 122:
            out.append((b - 97 + 13) % 26 + 97)
        else:
            out.append(b)
    return bytes(out)


def wrap(flag):
    step1 = rot13(flag)
    step2 = bytes(step1[i] ^ KEY[i % len(KEY)] for i in range(len(step1)))
    return base64.b64encode(step2).decode()


TEMPLATE = r"""/* triple-wrap -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

/* The flag, wrapped: base64( xor( rot13(flag), key ) ). Not the plaintext. */
static const char *blob  = "%BLOB%";
static const char *key   = "%KEY%";
static const char *decoy = "%DECOY%";  /* wrong on purpose */

static int b64val(int c)
{
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
}

static size_t b64decode(const char *in, unsigned char *out)
{
    size_t o = 0;
    int val = 0, bits = -8;
    for (const char *p = in; *p; p++) {
        int d = b64val(*p);
        if (d < 0) continue;
        val = (val << 6) | d;
        bits += 6;
        if (bits >= 0) {
            out[o++] = (unsigned char)((val >> bits) & 0xFF);
            bits -= 8;
        }
    }
    return o;
}

static unsigned char rot13c(unsigned char b)
{
    if (b >= 'A' && b <= 'Z') return (unsigned char)((b - 'A' + 13) % 26 + 'A');
    if (b >= 'a' && b <= 'z') return (unsigned char)((b - 'a' + 13) % 26 + 'a');
    return b;
}

static size_t unwrap(unsigned char *out)
{
    unsigned char tmp[256];
    size_t n = b64decode(blob, tmp);
    size_t klen = strlen(key);
    for (size_t i = 0; i < n; i++)
        out[i] = rot13c((unsigned char)(tmp[i] ^ key[i % klen]));
    out[n] = 0;
    return n;
}

int main(int argc, char **argv)
{
    unsigned char flag[256];
    char buf[256];

    printf("=== triple-wrap ===\n");
    printf("hint: the flag is %s (definitely)\n", decoy);

    if (argc >= 2) {
        strncpy(buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
    } else {
        printf("flag? ");
        if (!fgets(buf, sizeof(buf), stdin)) return 1;
        size_t n = strlen(buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    unwrap(flag);
    if (strcmp(buf, (char *)flag) == 0) {
        printf("[+] correct!\n");
        return 0;
    }
    printf("[-] wrong.\n");
    return 1;
}
"""


def main():
    import os

    blob = wrap(FLAG)
    c = TEMPLATE.replace("%BLOB%", blob)
    c = c.replace("%KEY%", KEY.decode())
    c = c.replace("%DECOY%", DECOY.decode())
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chall.c")
    with open(out, "w") as f:
        f.write(c)
    print("wrote", out)
    print("blob =", blob)
    print("flag =", FLAG.decode())


if __name__ == "__main__":
    main()
