#!/usr/bin/env python3
"""
Dev-only generator for the 'maze-vm' reverse challenge.  NOT shipped to players.

It emits src/program.h, which chall.c embeds.  The header carries a single
opaque blob:

    magic "MZVMv1\0\0"
    xor_seed  (u8)          rolling-key seed
    xor_mul   (u8)          rolling-key multiplier
    plen      (u8)          passphrase length
    prog_len  (u16 LE)      obfuscated bytecode length
    prog_obf[prog_len]      bytecode, rolling-XOR obfuscated
    target[plen]            F(passphrase): the values the VM must match

There is NO plaintext flag and NO plaintext passphrase in the output: only the
transformed image target = F(passphrase) is stored.  The passphrase (== the
inner flag text) is reconstructed at runtime only when the correct input is
fed in, and printed as NCTF{<passphrase>}.

The transform F is a bijection over the 16-byte space (per-byte add / modular
multiply / xor / bit-rotate, plus one whole-array byte permutation), so exactly
one input validates.
"""

# ---- the accepted input == the inner flag text (never stored in the binary) --
PASSPHRASE = b"m4ze_vm_thr34d3d"        # 16 bytes -> flag NCTF{m4ze_vm_thr34d3d}
PLEN = len(PASSPHRASE)
assert PLEN == 16

# ---- opcodes (chall.c and solve.py must agree) --------------------------------
NOP, HALT = 0x10, 0x11
PUSHI, LDIN, LDST, STST = 0x12, 0x13, 0x14, 0x15
POP, DUP, SWAP = 0x16, 0x17, 0x18
ADD, SUB, XOR, AND, OR = 0x19, 0x1A, 0x1B, 0x1C, 0x1D
MULMOD = 0x1E                            # (a*b) mod 256  -- modular multiply
ROL, ROR = 0x1F, 0x20                    # rotate top-of-stack, imm bit count
PERM = 0x21                              # followed by PLEN bytes: st[i]=old[perm[i]]
CMP = 0x22                               # pop b, pop a; if a!=b -> fail
JMP = 0x23                               # (reserved; unused by the checker)

# ---- fixed round constants ----------------------------------------------------
K1 = 0x8D        # odd -> invertible mod 256
K2 = 0x2B        # odd -> invertible mod 256
R1 = 3
R2 = 5

def prng(seed):
    x = seed & 0xFFFFFFFF
    while True:
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= (x >> 17)
        x ^= (x << 5) & 0xFFFFFFFF
        yield x & 0xFF

def build_tables():
    g = prng(0x9E3779B1)
    C1 = [next(g) for _ in range(PLEN)]
    X1 = [next(g) for _ in range(PLEN)]
    X2 = [next(g) for _ in range(PLEN)]
    perm = list(range(PLEN))
    for i in range(PLEN - 1, 0, -1):      # Fisher-Yates
        j = next(g) % (i + 1)
        perm[i], perm[j] = perm[j], perm[i]
    return C1, X1, X2, perm

def rol8(x, n): return ((x << n) | (x >> (8 - n))) & 0xFF

def transform(inp, C1, X1, X2, perm):
    st = [0] * PLEN
    for i in range(PLEN):                 # round A (per byte)
        b = inp[i]
        b = (b + C1[i]) & 0xFF
        b = (b * K1) & 0xFF
        b = b ^ X1[i]
        b = rol8(b, R1)
        st[i] = b
    st = [st[perm[i]] for i in range(PLEN)]   # round B: byte permute
    for i in range(PLEN):                 # round C (per byte)
        b = st[i]
        b = (b * K2) & 0xFF
        b = b ^ X2[i]
        b = rol8(b, R2)
        st[i] = b
    return st

def build_prog(C1, X1, X2, perm, target):
    p = []
    for i in range(PLEN):                 # round A
        p += [LDIN, i, PUSHI, C1[i], ADD, PUSHI, K1, MULMOD,
              PUSHI, X1[i], XOR, ROL, R1, STST, i]
    p += [PERM] + perm                    # round B
    for i in range(PLEN):                 # round C
        p += [LDST, i, PUSHI, K2, MULMOD, PUSHI, X2[i], XOR, ROL, R2, STST, i]
    for i in range(PLEN):                 # compare
        p += [LDST, i, PUSHI, target[i], CMP]
    p += [HALT]
    for b in p:
        assert 0 <= b <= 255, b
    return p

def obfuscate(prog, seed, mul):
    key = seed
    out = []
    for b in prog:
        o = b ^ key
        out.append(o)
        key = (key * mul + o) & 0xFF      # self-synchronizing keystream
    return out

def main():
    XOR_SEED, XOR_MUL = 0x5A, 0x1B
    C1, X1, X2, perm = build_tables()
    target = transform(list(PASSPHRASE), C1, X1, X2, perm)
    prog = build_prog(C1, X1, X2, perm, target)
    obf = obfuscate(prog, XOR_SEED, XOR_MUL)

    blob = list(b"MZVMv1\x00\x00")
    blob += [XOR_SEED, XOR_MUL, PLEN]
    blob += [len(obf) & 0xFF, (len(obf) >> 8) & 0xFF]
    blob += obf
    blob += target

    with open("program.h", "w") as f:
        f.write("/* GENERATED by src/gen.py -- do not edit. dev-only, not shipped. */\n")
        f.write("#ifndef PROGRAM_H\n#define PROGRAM_H\n\n")
        f.write("static const unsigned char BLOB[] = {\n")
        for i in range(0, len(blob), 12):
            f.write("    " + ",".join("0x%02x" % b for b in blob[i:i + 12]) + ",\n")
        f.write("};\n")
        f.write("#define BLOB_LEN %d\n\n" % len(blob))
        f.write("#endif\n")

    # sanity: exactly one input validates <=> transform is a bijection
    assert transform(list(PASSPHRASE), C1, X1, X2, perm) == target
    print("[gen] passphrase len=%d prog_len=%d blob_len=%d" % (PLEN, len(prog), len(blob)))
    print("[gen] flag would be: NCTF{%s}" % PASSPHRASE.decode())

if __name__ == "__main__":
    main()
