/* packed-vm-lite -- reverse challenge.
 *
 * A tiny custom bytecode interpreter validates a 24-character serial. There is
 * no flag string in this binary: on a correct serial it prints
 *     CTF{<the serial you typed>}
 * so the flag can only be learned by producing the serial the VM accepts.
 *
 * Build: gcc -O2 -s -o vmcheck src/vm.c   (program.h is generated by gen.py)
 *
 * The ISA is a small register+stack machine. Opcodes are 1 byte; a few carry a
 * 1-byte immediate. See the switch() below for exact semantics.
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>

#include "program.h"

/* One decoy: a plausible-but-unused "key" constant so a strings/grep pass has
 * something to chase. It is never read by the VM. Refutable in minutes by
 * checking that nothing references it. */
static const char decoy_key[] __attribute__((used)) =
    "vault_master_key=0xDEADBEEFCAFEBABE";

#define STACK_MAX 256
#define NREG 16

static uint8_t rotl8(uint8_t v, int n) {
    n &= 7;
    return (uint8_t)((v << n) | (v >> (8 - n)));
}
static uint8_t rotr8(uint8_t v, int n) {
    n &= 7;
    return (uint8_t)((v >> n) | (v << (8 - n)));
}

/* Run PROG over the input serial. Returns regs[6] (1 == accepted). */
static int run_vm(const uint8_t *input, int inlen) {
    uint8_t st[STACK_MAX];
    int sp = 0;
    uint8_t reg[NREG];
    memset(reg, 0, sizeof(reg));

    size_t pc = 0;
    int steps = 0;

    #define PUSH(x) do { if (sp < STACK_MAX) st[sp++] = (uint8_t)(x); } while (0)
    #define POP()   (sp > 0 ? st[--sp] : 0)

    while (pc < PROG_LEN && steps++ < 100000) {
        uint8_t op = PROG[pc++];
        switch (op) {
        case 0x00: /* NOP */ break;
        case 0x01: /* PUSH imm */ PUSH(PROG[pc++]); break;
        case 0x02: /* POP */ (void)POP(); break;
        case 0x03: /* DUP */ { uint8_t a = POP(); PUSH(a); PUSH(a); } break;
        case 0x04: /* SWAP */ { uint8_t a = POP(), b = POP(); PUSH(a); PUSH(b); } break;
        case 0x05: /* LDR imm */ PUSH(reg[PROG[pc++] & 0x0F]); break;
        case 0x06: /* STR imm */ reg[PROG[pc++] & 0x0F] = POP(); break;
        case 0x07: /* INC imm */ reg[PROG[pc++] & 0x0F]++; break;
        case 0x08: /* DEC imm */ reg[PROG[pc++] & 0x0F]--; break;
        case 0x09: /* LOADR */ { uint8_t i = POP();
                     PUSH(i < inlen ? input[i] : 0); } break;
        case 0x0A: /* LOADK */ { uint8_t i = POP();
                     PUSH(i < SERIAL_LEN ? VMKEY[i] : 0); } break;
        case 0x0B: /* LOADT */ { uint8_t i = POP();
                     PUSH(i < SERIAL_LEN ? VMTARGET[i] : 0); } break;
        case 0x0C: /* ADD */ { uint8_t a = POP(), b = POP(); PUSH(a + b); } break;
        case 0x0D: /* SUB */ { uint8_t a = POP(), b = POP(); PUSH(b - a); } break;
        case 0x0E: /* XOR */ { uint8_t a = POP(), b = POP(); PUSH(a ^ b); } break;
        case 0x0F: /* AND */ { uint8_t a = POP(), b = POP(); PUSH(a & b); } break;
        case 0x10: /* OR  */ { uint8_t a = POP(), b = POP(); PUSH(a | b); } break;
        case 0x11: /* MUL */ { uint8_t a = POP(), b = POP(); PUSH(a * b); } break;
        case 0x12: /* ADDI imm */ { uint8_t a = POP(); PUSH(a + PROG[pc++]); } break;
        case 0x13: /* XORI imm */ { uint8_t a = POP(); PUSH(a ^ PROG[pc++]); } break;
        case 0x14: /* MULI imm */ { uint8_t a = POP(); PUSH(a * PROG[pc++]); } break;
        case 0x15: /* ANDI imm */ { uint8_t a = POP(); PUSH(a & PROG[pc++]); } break;
        case 0x16: /* ROLV */ { uint8_t amt = POP(), val = POP();
                     PUSH(rotl8(val, amt)); } break;
        case 0x17: /* RORV (unused) */ { uint8_t amt = POP(), val = POP();
                     PUSH(rotr8(val, amt)); } break;
        case 0x18: /* NOT (unused) */ { uint8_t a = POP(); PUSH(~a); } break;
        case 0x19: /* CMPEQ */ { uint8_t a = POP(), b = POP();
                     PUSH(a == b ? 1 : 0); } break;
        case 0x1A: /* LEN */ PUSH((uint8_t)inlen); break;
        case 0x1B: /* CHKLEN imm */ { uint8_t n = PROG[pc++];
                     if (inlen != n) reg[3] = 1; } break;
        case 0x1C: /* JMP imm */ pc = PROG[pc]; break;
        case 0x1D: /* JZ imm */ { uint8_t t = PROG[pc++];
                     if (POP() == 0) pc = t; } break;
        case 0x1E: /* JNZ imm */ { uint8_t t = PROG[pc++];
                     if (POP() != 0) pc = t; } break;
        case 0x1F: /* HALT */ pc = PROG_LEN; break;
        default: /* unknown opcode -> abort */ pc = PROG_LEN; break;
        }
    }
    #undef PUSH
    #undef POP
    return reg[6];
}

int main(void) {
    char buf[128];

    fprintf(stderr, "Enter serial: ");
    fflush(stderr);
    if (!fgets(buf, sizeof(buf), stdin)) {
        fprintf(stderr, "no input\n");
        return 1;
    }
    /* strip trailing newline(s) */
    size_t n = strlen(buf);
    while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;

    if (run_vm((const uint8_t *)buf, (int)n)) {
        /* flag = CTF{ + serial + } ; never stored, rebuilt from your input */
        printf("Correct!\nCTF{%s}\n", buf);
        return 0;
    }
    printf("Wrong serial.\n");
    return 1;
}
