#!/usr/bin/env python3
"""Generate enc.h: the flag XOR-encoded with KEY so it is not readable via
`strings`. The same KEY is compiled into win() and applied at reveal time."""

FLAG = b"NCTF{ret2win_no_canary_no_pie_smashed}"
KEY = 0x5A


def main() -> None:
    enc = bytes(b ^ KEY for b in FLAG)
    body = ", ".join(f"0x{b:02x}" for b in enc)
    with open("enc.h", "w") as fh:
        fh.write("/* generated by gen.py -- do not edit */\n")
        fh.write(f"static const int enc_len = {len(enc)};\n")
        fh.write(f"static const unsigned char enc[{len(enc)}] = {{ {body} }};\n")


if __name__ == "__main__":
    main()
