/* stack-vm -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

/* Bytecode program: applied per input byte by the VM below. */
static const unsigned char prog[12] = { 0x01, 0x3d, 0x02, 0x11, 0x04, 0x03, 0x06, 0x03, 0x07, 0x05, 0x02, 0xff };

/* target[i] = VM(program, i, key[i]). Key/flag are not stored as plaintext. */
static const unsigned char target[17] = { 0xf2, 0xfe, 0xf2, 0x5c, 0x12, 0xe5, 0x73, 0x4b, 0x7a, 0xe2, 0x78, 0x7e, 0x24, 0xc3, 0x7d, 0xbb, 0x9c };

/* flag_enc[i] = flag[i] ^ key[i % KLEN]. Revealed only with the right key. */
static const unsigned char flag_enc[30] = { 0x3a, 0x31, 0x60, 0x25, 0x1e, 0x37, 0x40, 0x06, 0x57, 0x00, 0x02, 0x1f, 0x3e, 0x0c, 0x15, 0x17, 0x7e, 0x00, 0x1a, 0x07, 0x3c, 0x16, 0x2b, 0x40, 0x0b, 0x58, 0x00, 0x00, 0x00, 0x22 };

#define KLEN 17
#define FLEN 30

static unsigned char rol8(unsigned char v, int r)
{
    r &= 7;
    return (unsigned char)((v << r) | (v >> (8 - r)));
}

static unsigned char ror8(unsigned char v, int r)
{
    r &= 7;
    return (unsigned char)((v >> r) | (v << (8 - r)));
}

/* Run the bytecode once for input byte x at position i; return the accumulator. */
static unsigned char vm(int i, unsigned char x)
{
    unsigned char acc = x;
    size_t pc = 0;
    while (pc < sizeof(prog)) {
        unsigned char op = prog[pc++];
        if (op == 0xFF) break;
        unsigned char imm = 0;
        if (op >= 0x01 && op <= 0x05) imm = prog[pc++];
        switch (op) {
            case 0x01: acc ^= imm; break;
            case 0x02: acc = (unsigned char)(acc + imm); break;
            case 0x03: acc = (unsigned char)(acc - imm); break;
            case 0x04: acc = rol8(acc, imm); break;
            case 0x05: acc = ror8(acc, imm); break;
            case 0x06: acc ^= (unsigned char)(i & 0xFF); break;
        }
    }
    return acc;
}

static int check(const unsigned char *p, size_t n)
{
    if (n != KLEN) return 0;
    for (size_t i = 0; i < KLEN; i++)
        if (vm((int)i, p[i]) != target[i]) return 0;
    return 1;
}

static void reveal(const unsigned char *p)
{
    unsigned char out[FLEN + 1];
    for (size_t i = 0; i < FLEN; i++)
        out[i] = (unsigned char)(flag_enc[i] ^ p[i % KLEN]);
    out[FLEN] = 0;
    printf("[+] key accepted. flag: %s\n", out);
}

int main(int argc, char **argv)
{
    unsigned char buf[256];
    size_t n;

    printf("=== stack-vm ===\n");
    if (argc >= 2) {
        strncpy((char *)buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen((char *)buf);
    } else {
        printf("key? ");
        if (!fgets((char *)buf, sizeof(buf), stdin)) return 1;
        n = strlen((char *)buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check(buf, n)) {
        reveal(buf);
        return 0;
    }
    printf("[-] rejected.\n");
    return 1;
}
