#!/usr/bin/env python3
"""
Developer-only generator for the 'stack-vm' reverse challenge.

The binary embeds a tiny accumulator VM and a bytecode program. To validate a
key, the VM is run once per input byte (accumulator initialised to that byte,
with the byte index available as a position register) and the result is compared
to an embedded target[]. On a full match, a second array flag_enc[] is XORed
with the key (repeated) to reveal the flag.

Instruction set (opcode, optional 1-byte immediate):

    0x01 XOR imm    acc ^= imm
    0x02 ADD imm    acc = (acc + imm) & 0xFF
    0x03 SUB imm    acc = (acc - imm) & 0xFF
    0x04 ROL imm    acc = rol8(acc, imm)
    0x05 ROR imm    acc = ror8(acc, imm)
    0x06 XORI       acc ^= (i & 0xFF)        (position mix, no operand)
    0xFF HALT

Every op is invertible, so the key is uniquely determined by target[]. The flag
is never stored as plaintext. This file is NOT shipped to players.
"""

KEY = b"tr4ce_th3_vm_ops!"
FLAG = b"NCTF{h4nd_traced_th3_st4ck_vm}"

XOR, ADD, SUB, ROL, ROR, XORI, HALT = 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0xFF

PROGRAM = [
    (XOR, 0x3D),
    (ADD, 0x11),
    (ROL, 3),
    (XORI, None),
    (SUB, 0x07),
    (ROR, 2),
    (HALT, None),
]


def rol8(v, r):
    r &= 7
    return ((v << r) | (v >> (8 - r))) & 0xFF


def ror8(v, r):
    r &= 7
    return ((v >> r) | (v << (8 - r))) & 0xFF


def run(i, x):
    acc = x & 0xFF
    for op, imm in PROGRAM:
        if op == XOR:
            acc ^= imm
        elif op == ADD:
            acc = (acc + imm) & 0xFF
        elif op == SUB:
            acc = (acc - imm) & 0xFF
        elif op == ROL:
            acc = rol8(acc, imm)
        elif op == ROR:
            acc = ror8(acc, imm)
        elif op == XORI:
            acc ^= i & 0xFF
        elif op == HALT:
            break
    return acc & 0xFF


def bytecode():
    out = []
    for op, imm in PROGRAM:
        out.append(op)
        if op in (XOR, ADD, SUB, ROL, ROR):
            out.append(imm)
    return out


def carr(name, data):
    body = ", ".join("0x%02x" % b for b in data)
    return "static const unsigned char %s[%d] = { %s };" % (name, len(data), body)


TEMPLATE = r"""/* stack-vm -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

/* Bytecode program: applied per input byte by the VM below. */
%PROG%

/* target[i] = VM(program, i, key[i]). Key/flag are not stored as plaintext. */
%TARGET%

/* flag_enc[i] = flag[i] ^ key[i %% KLEN]. Revealed only with the right key. */
%FLAGENC%

#define KLEN %KLEN%
#define FLEN %FLEN%

static unsigned char rol8(unsigned char v, int r)
{
    r &= 7;
    return (unsigned char)((v << r) | (v >> (8 - r)));
}

static unsigned char ror8(unsigned char v, int r)
{
    r &= 7;
    return (unsigned char)((v >> r) | (v << (8 - r)));
}

/* Run the bytecode once for input byte x at position i; return the accumulator. */
static unsigned char vm(int i, unsigned char x)
{
    unsigned char acc = x;
    size_t pc = 0;
    while (pc < sizeof(prog)) {
        unsigned char op = prog[pc++];
        if (op == 0xFF) break;
        unsigned char imm = 0;
        if (op >= 0x01 && op <= 0x05) imm = prog[pc++];
        switch (op) {
            case 0x01: acc ^= imm; break;
            case 0x02: acc = (unsigned char)(acc + imm); break;
            case 0x03: acc = (unsigned char)(acc - imm); break;
            case 0x04: acc = rol8(acc, imm); break;
            case 0x05: acc = ror8(acc, imm); break;
            case 0x06: acc ^= (unsigned char)(i & 0xFF); break;
        }
    }
    return acc;
}

static int check(const unsigned char *p, size_t n)
{
    if (n != KLEN) return 0;
    for (size_t i = 0; i < KLEN; i++)
        if (vm((int)i, p[i]) != target[i]) return 0;
    return 1;
}

static void reveal(const unsigned char *p)
{
    unsigned char out[FLEN + 1];
    for (size_t i = 0; i < FLEN; i++)
        out[i] = (unsigned char)(flag_enc[i] ^ p[i %% KLEN]);
    out[FLEN] = 0;
    printf("[+] key accepted. flag: %s\n", out);
}

int main(int argc, char **argv)
{
    unsigned char buf[256];
    size_t n;

    printf("=== stack-vm ===\n");
    if (argc >= 2) {
        strncpy((char *)buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen((char *)buf);
    } else {
        printf("key? ");
        if (!fgets((char *)buf, sizeof(buf), stdin)) return 1;
        n = strlen((char *)buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check(buf, n)) {
        reveal(buf);
        return 0;
    }
    printf("[-] rejected.\n");
    return 1;
}
"""


def main():
    import os

    target = [run(i, KEY[i]) for i in range(len(KEY))]
    flag_enc = [FLAG[i] ^ KEY[i % len(KEY)] for i in range(len(FLAG))]

    c = TEMPLATE.replace("%PROG%", carr("prog", bytecode()))
    c = c.replace("%TARGET%", carr("target", target))
    c = c.replace("%FLAGENC%", carr("flag_enc", flag_enc))
    c = c.replace("%KLEN%", str(len(KEY)))
    c = c.replace("%FLEN%", str(len(FLAG)))
    c = c.replace(") ^ p[i %% KLEN]", ") ^ p[i % KLEN]")
    c = c.replace("i %% KLEN", "i % KLEN")

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chall.c")
    with open(out, "w") as f:
        f.write(c)
    print("wrote", out)
    print("key  =", KEY.decode())
    print("flag =", FLAG.decode())


if __name__ == "__main__":
    main()
