/* byte-drift -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

/* target[] = transform(flag). The flag itself is never stored as plaintext. */
static const unsigned char target[30] = { 0xf6, 0x69, 0x57, 0x39, 0x8d, 0x83, 0x9f, 0x79, 0x15, 0xf8, 0xc5, 0xac, 0xbb, 0x17, 0x94, 0x12, 0x80, 0x96, 0x88, 0xf5, 0x87, 0x17, 0xf2, 0x72, 0xb6, 0x0b, 0x3e, 0x3f, 0x23, 0x33 };

#define FLEN 30

static unsigned char rol8(unsigned char v, int r)
{
    return (unsigned char)((v << r) | (v >> (8 - r)));
}

static int check(const unsigned char *p, size_t n)
{
    size_t i;
    if (n != FLEN) return 0;
    for (i = 0; i < FLEN; i++) {
        unsigned char t = rol8((unsigned char)((p[i] + (i * 3 + 7)) & 0xFF),
                               (int)((i % 7) + 1)) ^ 0x5C;
        if (t != target[i]) return 0;
    }
    return 1;
}

int main(int argc, char **argv)
{
    unsigned char buf[256];
    size_t n;

    printf("=== byte-drift lock ===\n");
    if (argc >= 2) {
        strncpy((char *)buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen((char *)buf);
    } else {
        printf("passphrase: ");
        if (!fgets((char *)buf, sizeof(buf), stdin)) return 1;
        n = strlen((char *)buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check(buf, n)) {
        printf("[+] unlocked. the passphrase IS the flag.\n");
        return 0;
    }
    printf("[-] locked.\n");
    return 1;
}
