#!/usr/bin/env python3
"""
Developer-only generator for the 'byte-drift' reverse challenge.

The binary reads a passphrase and validates it one byte at a time against an
embedded array ``target[]`` using an invertible per-byte transform that mixes a
rotate, a position-dependent add, and an xor:

    enc[i] = ROL8( (p[i] + (i*3 + 7)) & 0xFF , (i % 7) + 1 ) ^ 0x5C

The transform is fully invertible, so the correct input is uniquely determined
by ``target[]`` -- there is no keystream and no second array. The flag *is* the
passphrase, so it never appears in the file as plaintext; only its transformed
image does.

This file is NOT shipped to players. Players get the compiled ELF ``chall``.
"""

FLAG = b"NCTF{inv3rt_th3_drift_by_h4nd}"


def rol8(v, r):
    return ((v << r) | (v >> (8 - r))) & 0xFF


def transform(p):
    return [
        rol8((p[i] + (i * 3 + 7)) & 0xFF, (i % 7) + 1) ^ 0x5C for i in range(len(p))
    ]


def carr(name, data):
    body = ", ".join("0x%02x" % b for b in data)
    return "static const unsigned char %s[%d] = { %s };" % (name, len(data), body)


TEMPLATE = r"""/* byte-drift -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

/* target[] = transform(flag). The flag itself is never stored as plaintext. */
%TARGET%

#define FLEN %FLEN%

static unsigned char rol8(unsigned char v, int r)
{
    return (unsigned char)((v << r) | (v >> (8 - r)));
}

static int check(const unsigned char *p, size_t n)
{
    size_t i;
    if (n != FLEN) return 0;
    for (i = 0; i < FLEN; i++) {
        unsigned char t = rol8((unsigned char)((p[i] + (i * 3 + 7)) & 0xFF),
                               (int)((i % 7) + 1)) ^ 0x5C;
        if (t != target[i]) return 0;
    }
    return 1;
}

int main(int argc, char **argv)
{
    unsigned char buf[256];
    size_t n;

    printf("=== byte-drift lock ===\n");
    if (argc >= 2) {
        strncpy((char *)buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen((char *)buf);
    } else {
        printf("passphrase: ");
        if (!fgets((char *)buf, sizeof(buf), stdin)) return 1;
        n = strlen((char *)buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check(buf, n)) {
        printf("[+] unlocked. the passphrase IS the flag.\n");
        return 0;
    }
    printf("[-] locked.\n");
    return 1;
}
"""


def main():
    import os

    target = transform(FLAG)
    c = TEMPLATE.replace("%TARGET%", carr("target", target))
    c = c.replace("%FLEN%", str(len(FLAG)))
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chall.c")
    with open(out, "w") as f:
        f.write(c)
    print("wrote", out)
    print("flag =", FLAG.decode())


if __name__ == "__main__":
    main()
