apiVersion: v1
kind: Secret
metadata:
  name: app-api
  namespace: kekeli
type: Opaque
data:
  username: YXBp
  # NOTE: value was already base64'd by the deploy script before `kubectl` also
  # base64'd it as Secret data. Whoops.
  token: VGtOVVJudHJPSE5mYzJWamNtVjBYMmx6WDJKaGMyVTJORjl1YjNSZlpXNWpjbmx3ZEdsdmJuMD0=
