/* keygen-me -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

static const char *ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

/* Chained-constraint targets. The flag is NOT stored, here or at runtime. */
static const unsigned char t[48] = { 9, 22, 21, 8, 30, 7, 11, 0, 17, 14, 26, 21, 6, 5, 1, 2, 17, 18, 19, 4, 18, 27, 1, 25, 21, 12, 18, 25, 9, 21, 13, 25, 4, 9, 2, 16, 20, 20, 20, 2, 16, 13, 16, 26, 19, 23, 17, 10 };

#define N 48

static int symval(char c)
{
    const char *p = strchr(ALPHABET, c);
    return p ? (int)(p - ALPHABET) : -1;
}

static int check(const char *key)
{
    int v[N];
    int n = 0;
    for (const char *p = key; *p && n < N; p++) {
        if (*p == '-') continue;
        int s = symval(*p);
        if (s < 0) return 0;
        v[n++] = s;
    }
    if (n != N) return 0;
    if (v[0] != t[0]) return 0;
    for (int i = 1; i < N; i++)
        if ((v[i] + 3 * v[i - 1] + 7 * i + 0x1B) % 32 != t[i]) return 0;
    return 1;
}

int main(int argc, char **argv)
{
    char buf[256];

    printf("=== ACME license validator ===\n");
    if (argc >= 2) {
        strncpy(buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
    } else {
        printf("license key: ");
        if (!fgets(buf, sizeof(buf), stdin)) return 1;
        size_t n = strlen(buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check(buf)) {
        printf("[+] license accepted. (decode the key to read the flag)\n");
        return 0;
    }
    printf("[-] invalid license.\n");
    return 1;
}
