#!/usr/bin/env python3
"""
Developer-only generator for the 'keygen-me' reverse challenge.

The program validates a license key of 48 base32 symbols (RFC4648 alphabet
A-Z2-7), grouped 8-8-8-8-8-8 with '-' separators. Each symbol is a 5-bit value
v[i] (its index in the alphabet). The validator enforces a chained constraint
system against an embedded target array t[]:

    v[0]                            == t[0]
    (v[i] + 3*v[i-1] + 7*i + 0x1B) % 32 == t[i]      for i >= 1

The system has a UNIQUE solution obtainable by forward substitution. That unique
v[] is exactly the base32 encoding of the flag, so repacking the solved 5-bit
groups into bytes yields NCTF{...}. The flag never appears in the binary, not
even at runtime. This file is NOT shipped to players.
"""

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
FLAG = b"NCTF{keyg3n_solv3d_th3_serial}"  # 30 bytes -> 240 bits -> 48 symbols


def to_symbols(data):
    bits = "".join("{:08b}".format(b) for b in data)
    assert len(bits) % 5 == 0, "flag must be a multiple of 5 bits"
    return [int(bits[i : i + 5], 2) for i in range(0, len(bits), 5)]


def targets(v):
    t = [v[0]]
    for i in range(1, len(v)):
        t.append((v[i] + 3 * v[i - 1] + 7 * i + 0x1B) % 32)
    return t


TEMPLATE = r"""/* keygen-me -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

static const char *ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

/* Chained-constraint targets. The flag is NOT stored, here or at runtime. */
%TARGET%

#define N %N%

static int symval(char c)
{
    const char *p = strchr(ALPHABET, c);
    return p ? (int)(p - ALPHABET) : -1;
}

static int check(const char *key)
{
    int v[N];
    int n = 0;
    for (const char *p = key; *p && n < N; p++) {
        if (*p == '-') continue;
        int s = symval(*p);
        if (s < 0) return 0;
        v[n++] = s;
    }
    if (n != N) return 0;
    if (v[0] != t[0]) return 0;
    for (int i = 1; i < N; i++)
        if ((v[i] + 3 * v[i - 1] + 7 * i + 0x1B) %% 32 != t[i]) return 0;
    return 1;
}

int main(int argc, char **argv)
{
    char buf[256];

    printf("=== ACME license validator ===\n");
    if (argc >= 2) {
        strncpy(buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
    } else {
        printf("license key: ");
        if (!fgets(buf, sizeof(buf), stdin)) return 1;
        size_t n = strlen(buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check(buf)) {
        printf("[+] license accepted. (decode the key to read the flag)\n");
        return 0;
    }
    printf("[-] invalid license.\n");
    return 1;
}
"""


def main():
    import os

    v = to_symbols(FLAG)
    t = targets(v)
    body = ", ".join(str(x) for x in t)
    decl = "static const unsigned char t[%d] = { %s };" % (len(t), body)
    c = TEMPLATE.replace("%TARGET%", decl).replace("%N%", str(len(t)))
    c = c.replace(") %% 32 !=", ") % 32 !=")

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chall.c")
    with open(out, "w") as f:
        f.write(c)

    serial = "".join(ALPHABET[x] for x in v)
    grouped = "-".join(serial[i : i + 8] for i in range(0, len(serial), 8))
    print("wrote", out)
    print("serial =", grouped)
    print("flag   =", FLAG.decode())


if __name__ == "__main__":
    main()
