/* strings-lie -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

/* The fake flag. This is the ONLY flag-looking string in the binary and it
 * is a decoy. A tool that greps strings(1) lands here. */
static const char *decoy = "NCTF{y0u_grepp3d_th3_f4ke_0ne}";

/* Transformed target of the correct passphrase (see arithmetic below). */
static const unsigned char target[23] = { 0x32, 0x3e, 0x3e, 0x83, 0x53, 0x64, 0x32, 0x62, 0x6d, 0xab, 0x4e, 0x87, 0x92, 0x8c, 0x97, 0x71, 0xab, 0x9d, 0x86, 0xba, 0xfd, 0xca, 0xdb };

/* The real flag, stored XORed with the passphrase (keystream = pass repeated).
 * It is never present in the binary as plaintext. */
static const unsigned char flag_enc[31] = { 0x3b, 0x2d, 0x23, 0x77, 0x15, 0x17, 0x2b, 0x06, 0x59, 0x5d, 0x38, 0x1e, 0x3e, 0x18, 0x59, 0x3a, 0x3d, 0x0b, 0x3a, 0x09, 0x50, 0x31, 0x10, 0x1d, 0x0b, 0x28, 0x52, 0x5e, 0x00, 0x3a, 0x09 };

#define PLEN 23
#define FLEN 31

static int check(const unsigned char *p, size_t n)
{
    size_t i;
    if (n != PLEN) return 0;
    for (i = 0; i < PLEN; i++) {
        unsigned char t = (unsigned char)(((p[i] ^ 0x5A) + (i * 7 + 3)) & 0xFF);
        if (t != target[i]) return 0;
    }
    return 1;
}

static void reveal(const unsigned char *p)
{
    unsigned char out[FLEN + 1];
    size_t i;
    for (i = 0; i < FLEN; i++)
        out[i] = (unsigned char)(flag_enc[i] ^ p[i % PLEN]);
    out[FLEN] = 0;
    printf("[+] correct. flag: %s\n", out);
}

int main(int argc, char **argv)
{
    unsigned char buf[256];
    size_t n;

    /* Loud, obvious, and wrong. */
    printf("=== super-secret vault v0.3 ===\n");
    printf("hint: the flag is %s ... or is it?\n", decoy);

    if (argc >= 2) {
        strncpy((char *)buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen((char *)buf);
    } else {
        printf("enter passphrase: ");
        if (!fgets((char *)buf, sizeof(buf), stdin)) return 1;
        n = strlen((char *)buf);
        while (n && (buf[n-1] == '\n' || buf[n-1] == '\r')) buf[--n] = 0;
    }

    if (check(buf, n)) {
        reveal(buf);
        return 0;
    }
    printf("[-] nope.\n");
    return 1;
}
