#!/usr/bin/env python3
"""
Developer-only generator for the 'strings-lie' reverse challenge.
Computes the embedded target[] and flag_enc[] arrays and emits chall.c.

This file is NOT shipped to players (it lives only in the repo). Players
receive the compiled ELF 'chall' plus the description.

Design
------
The binary reads a passphrase (argv[1] or stdin). It applies an invertible
per-byte arithmetic transform and compares against target[]. If every byte
matches, it decrypts flag_enc[] with the passphrase and prints the real flag.

Transform (per byte i, 0-based):
    t[i] = ( ((P[i] ^ 0x5A) + (i*7 + 3)) & 0xFF )
Inverse (used by the solver):
    P[i] = ( ((t[i] - (i*7 + 3)) & 0xFF) ^ 0x5A )

Flag is stored XORed with the passphrase repeated (keystream = P repeated),
so the plaintext flag never appears in the binary. strings(1) only reveals
the decoy.
"""

PASS  = b"unw1nd_th3_math_by_h4nd"          # the real key (23 bytes)
FLAG  = b"CTF{str1ngs_l1e_read_the_c0de}"    # the real flag (static)
DECOY = b"CTF{y0u_grepp3d_th3_f4ke_0ne}"     # obvious strings(1) hit

def transform(P):
    return [ (((P[i] ^ 0x5A) + (i * 7 + 3)) & 0xFF) for i in range(len(P)) ]

def enc_flag(FLAG, P):
    return [ FLAG[i] ^ P[i % len(P)] for i in range(len(FLAG)) ]

def carr(name, data):
    body = ", ".join("0x%02x" % b for b in data)
    return "static const unsigned char %s[%d] = { %s };" % (name, len(data), body)

def main():
    target   = transform(PASS)
    flag_enc = enc_flag(FLAG, PASS)

    c = r'''/* strings-lie -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdio.h>
#include <string.h>

/* The fake flag. This is the ONLY flag-looking string in the binary and it
 * is a decoy. A tool that greps strings(1) lands here. */
static const char *decoy = "%DECOY%";

/* Transformed target of the correct passphrase (see arithmetic below). */
%TARGET%

/* The real flag, stored XORed with the passphrase (keystream = pass repeated).
 * It is never present in the binary as plaintext. */
%FLAGENC%

#define PLEN %PLEN%
#define FLEN %FLEN%

static int check(const unsigned char *p, size_t n)
{
    size_t i;
    if (n != PLEN) return 0;
    for (i = 0; i < PLEN; i++) {
        unsigned char t = (unsigned char)(((p[i] ^ 0x5A) + (i * 7 + 3)) & 0xFF);
        if (t != target[i]) return 0;
    }
    return 1;
}

static void reveal(const unsigned char *p)
{
    unsigned char out[FLEN + 1];
    size_t i;
    for (i = 0; i < FLEN; i++)
        out[i] = (unsigned char)(flag_enc[i] ^ p[i % PLEN]);
    out[FLEN] = 0;
    printf("[+] correct. flag: %s\n", out);
}

int main(int argc, char **argv)
{
    unsigned char buf[256];
    size_t n;

    /* Loud, obvious, and wrong. */
    printf("=== super-secret vault v0.3 ===\n");
    printf("hint: the flag is %s ... or is it?\n", decoy);

    if (argc >= 2) {
        strncpy((char *)buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen((char *)buf);
    } else {
        printf("enter passphrase: ");
        if (!fgets((char *)buf, sizeof(buf), stdin)) return 1;
        n = strlen((char *)buf);
        while (n && (buf[n-1] == '\n' || buf[n-1] == '\r')) buf[--n] = 0;
    }

    if (check(buf, n)) {
        reveal(buf);
        return 0;
    }
    printf("[-] nope.\n");
    return 1;
}
'''
    c = c.replace("%DECOY%", DECOY.decode())
    c = c.replace("%TARGET%", carr("target", target))
    c = c.replace("%FLAGENC%", carr("flag_enc", flag_enc))
    c = c.replace("%PLEN%", str(len(PASS)))
    c = c.replace("%FLEN%", str(len(FLAG)))

    import os
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chall.c")
    with open(out, "w") as f:
        f.write(c)
    print("wrote", out)
    print("pass =", PASS.decode())
    print("flag =", FLAG.decode())

if __name__ == "__main__":
    main()
