/* crc-forge -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/* table[i] = crc32( {i & 0xFF, flag[i]} ). No flag byte is stored directly. */
static const uint32_t table[28] = { 0xd0bd7e68u, 0xb7173394u, 0x1fe9e590u, 0xf54ba599u, 0xe2627f4fu, 0xe815d658u, 0xa988a569u, 0xda23b4dau, 0x36d0f9e1u, 0x58ccf836u, 0x40e2b610u, 0xe629e647u, 0xd0b4c824u, 0xd5c39807u, 0x053a87a1u, 0x0f4d2eb6u, 0xf0cf4ccbu, 0x2fd8a438u, 0x804bb625u, 0x9fe6327bu, 0xd17cd5bau, 0x5fb53d73u, 0xa695eb4du, 0xe7e6961du, 0xea1b433eu, 0x8db10ec2u, 0x4e248932u, 0xc65bd4e4u };

#define FLEN 28

static uint32_t crc32_2(uint8_t a, uint8_t b)
{
    uint8_t msg[2] = { a, b };
    uint32_t crc = 0xFFFFFFFFu;
    for (int k = 0; k < 2; k++) {
        crc ^= msg[k];
        for (int j = 0; j < 8; j++)
            crc = (crc >> 1) ^ (0xEDB88320u & (uint32_t)(-(int32_t)(crc & 1)));
    }
    return crc ^ 0xFFFFFFFFu;
}

static int check(const unsigned char *p, size_t n)
{
    if (n != FLEN) return 0;
    for (size_t i = 0; i < FLEN; i++)
        if (crc32_2((uint8_t)(i & 0xFF), p[i]) != table[i]) return 0;
    return 1;
}

int main(int argc, char **argv)
{
    char buf[256];
    size_t n;

    printf("=== crc-forge ===\n");
    if (argc >= 2) {
        strncpy(buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen(buf);
    } else {
        printf("flag? ");
        if (!fgets(buf, sizeof(buf), stdin)) return 1;
        n = strlen(buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check((unsigned char *)buf, n)) {
        printf("[+] checksums match. that is the flag.\n");
        return 0;
    }
    printf("[-] checksum mismatch.\n");
    return 1;
}
