#!/usr/bin/env python3
"""
Developer-only generator for the 'crc-forge' reverse challenge.

The binary validates input using a per-byte CRC32 table. For each position i it
stores:

    table[i] = crc32( bytes([i & 0xFF, flag[i]]) )

i.e. the CRC of a two-byte message (position salt + flag byte). At runtime the
checker recomputes each CRC from the user's input and compares. Because each
entry depends on exactly one flag byte, every byte is independently recoverable
by brute-forcing all 256 possibilities against the stored CRC -- the position
salt makes the mapping unique per index. This file is NOT shipped.
"""

import binascii

FLAG = b"NCTF{crc32_le4ks_ev3ry_byt3}"


def table(flag):
    return [
        binascii.crc32(bytes([i & 0xFF, flag[i]])) & 0xFFFFFFFF
        for i in range(len(flag))
    ]


TEMPLATE = r"""/* crc-forge -- reverse challenge (auto-generated by gen.py; do not hand-edit) */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/* table[i] = crc32( {i & 0xFF, flag[i]} ). No flag byte is stored directly. */
%TABLE%

#define FLEN %FLEN%

static uint32_t crc32_2(uint8_t a, uint8_t b)
{
    uint8_t msg[2] = { a, b };
    uint32_t crc = 0xFFFFFFFFu;
    for (int k = 0; k < 2; k++) {
        crc ^= msg[k];
        for (int j = 0; j < 8; j++)
            crc = (crc >> 1) ^ (0xEDB88320u & (uint32_t)(-(int32_t)(crc & 1)));
    }
    return crc ^ 0xFFFFFFFFu;
}

static int check(const unsigned char *p, size_t n)
{
    if (n != FLEN) return 0;
    for (size_t i = 0; i < FLEN; i++)
        if (crc32_2((uint8_t)(i & 0xFF), p[i]) != table[i]) return 0;
    return 1;
}

int main(int argc, char **argv)
{
    char buf[256];
    size_t n;

    printf("=== crc-forge ===\n");
    if (argc >= 2) {
        strncpy(buf, argv[1], sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = 0;
        n = strlen(buf);
    } else {
        printf("flag? ");
        if (!fgets(buf, sizeof(buf), stdin)) return 1;
        n = strlen(buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }

    if (check((unsigned char *)buf, n)) {
        printf("[+] checksums match. that is the flag.\n");
        return 0;
    }
    printf("[-] checksum mismatch.\n");
    return 1;
}
"""


def main():
    import os

    t = table(FLAG)
    body = ", ".join("0x%08xu" % v for v in t)
    decl = "static const uint32_t table[%d] = { %s };" % (len(t), body)
    c = TEMPLATE.replace("%TABLE%", decl).replace("%FLEN%", str(len(FLAG)))
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chall.c")
    with open(out, "w") as f:
        f.write(c)
    print("wrote", out)
    print("flag =", FLAG.decode())


if __name__ == "__main__":
    main()
