#!/usr/bin/env python3
"""Generate enc.h: the flag XOR-encoded with KEY so it is not readable via
`strings`. reveal() applies the same KEY once the leaked cookie is echoed
back correctly."""

FLAG = b"NCTF{format_leak_stack_key_recovered}"
KEY = 0x4D


def main() -> None:
    enc = bytes(b ^ KEY for b in FLAG)
    body = ", ".join(f"0x{b:02x}" for b in enc)
    with open("enc.h", "w") as fh:
        fh.write("/* generated by gen.py -- do not edit */\n")
        fh.write(f"static const int enc_len = {len(enc)};\n")
        fh.write(f"static const unsigned char enc[{len(enc)}] = {{ {body} }};\n")


if __name__ == "__main__":
    main()
